### ISSUE TITLE
Wrong border color of tooltip on RadzenColumnSeries

### ISSUE THREAD

**Issue by eharbitz** [radzenhq/radzen-blazor#421]
**Describe the bug**

When using `RadzenColumnSeries` with custom `Fill`, the tooltip border color does not match the series color.

**To Reproduce**
1. Create a `RadzenChart`
2. Add a `RadzenColumnSeries` where the property `Fill` is set to some arbitrary color
4. Hover over the chart.
5. Notice how the border color for the tooltip does not match the color of the series in the chart.

Example code:

`<RadzenChart>
    <RadzenColumnSeries Data="@Series"
                        CategoryProperty="Group"
                        ValueProperty="Value"
                        Fill="red">
    </RadzenColumnSeries>
</RadzenChart>
`

**Expected behavior**
When using `Fill`, the color of the tooltip border should be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/15960296/162428991-9c241cd2-7a9d-4710-8a7e-02ef83e0a95b.png)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**
1. It does not make any difference if `Stroke` is also used
2. It seems like the bug should be fixed here: [Set bar and column series tooltip border to Fill or Fills if specified.
](https://github.com/radzenhq/radzen-blazor/commit/37907ed7f699dc51380cccdad67aff74aeeac480#diff-8c029d5c3044f60cabcb860b32656abcc3ecb93a68631ceb0518d95e6e008b65) Maybe something wrong with the `index` value?

**Comment by akorchev** [comment]
Should be addressed via https://github.com/radzenhq/radzen-blazor/commit/37907ed7f699dc51380cccdad67aff74aeeac480

**Comment by eharbitz** [comment]
> Should be addressed via [37907ed](https://github.com/radzenhq/radzen-blazor/commit/37907ed7f699dc51380cccdad67aff74aeeac480)

I would think so too, but it appears to not do it.

From same page:
![image](https://user-images.githubusercontent.com/15960296/162430750-e2b47a85-7dd4-4e41-89fb-1028ccde24f4.png)
Image caption: Bug fixed for areaseries

![image](https://user-images.githubusercontent.com/15960296/162430782-d6e43cb2-d636-4c12-b9ee-cee6e7ac475c.png)
Image caption: Not fixed for column series

**Comment by akorchev** [comment]
This commit has not been released yet.

**Comment by eharbitz** [comment]
I'm sorry :/

Thanks for fixing and responding this fast :)
